name: Node Continuous Integration

on:
  pull_request:
    branches: [master]
  # push:
  #   branches: [development]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install

      - name: Compile with Gulp
        uses: elstudio/actions-js-build/build@v2

      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: Compile
